# FUSE-070

Following [@clark2009] and [@kavetski2009], we will also illustrate the
approaches for FUSE-070, which is one of a set of conceptual models that are
broadly representative for commonly used conceptual hydrological models.
FUSE-070 consists of two storage states for an upper and a lower layer.
Hydrological flows are partioned into rainfall, evaporation, drainage, base
flow, and a surface runoff components.

Storage in the upper layer evolves over time as

$$
\frac{dS_1}{dt} = (p - q_{sx}) - e_1 - q_{12} - q_{ufof} = F_1
$$

And storage in the second layer

$$
\frac{dS_2}{dt} = q_{12} - q_b = F_2
$$

Evaporation is defined as

$$
\text{PET} \min \left( S_1^*, 1 \right)
$$

with

$$
S_1^* = \frac{S_1}{\phi_{tens} S_{1,max} }
$$

and $\phi_{tens}$ the fraction of tension storage in the upper layer, and

$$
0.05 \leq \phi_{tens} \leq 0.95
$$

The min function is not differentiable, which is problematic for many
algorithms such Newton-Raphson as they rely on derivatives.

Instead, it is approximated using a quadratically smoothed min function [@kavetski2007]

$$
\text{min}_S(a, b, m) = \text{min}(a, b) \approx \frac{1}{2} \left( a + b - \sqrt{(a - b)^2 + m} \right)
$$

where $m$ is a smoothing parameter.

$$
e_1 = \frac{\text{PET}}{2} \left( S_1^* + 1 - \sqrt{ ( S_1^* - 1 )^2 + m } \right)
$$

Drainage from the upper to deeper layer as

$$
q_{12} = k_u s_f ^ c
$$

Where $s_f$ is the saturation fraction

$$
s_f = \frac{S_1}{S_{1,max}}.
$$

With $k_u$ the interflow rate (mm/d) and $c$ the drainage exponent (-).

Base flow from the lower layer is

$$
q_b = \nu S_2
$$

With $\nu$ the base depletion rate (1/d).

And surface runoff

$$
q_{sx} = p \left[ 1 - \left( 1 - \frac{S_1}{S_{1,max}} \right) ^ b \right]
$$

With $b$ as the ARNO/VIC "b" exponent (-).

If the values of $b$ or $c$ are smaller than one, exponentiation may yield a
complex number if $S_1$ is negative. While the solver should never converge on
negative storage values, it may encounter negative values of $S_1$ while
solving. To ensure the formulation remains well-defined even for (slightly)
negative storage values, we ensure $s_f \in [0, 1]$. However, the clamp function

$$
\operatorname{clamp}(x, a, b) = operatorname{max}(a, operatorname{min}(b, x))
$$

is not differentiable. Instead we smooth quadratically


$$
\operatorname{clamp}_\text{s}(x, x_{\text{lo}}, x_{\text{hi}}, m) = x_{\text{lo}} + d \cdot y(x_{\text{norm}})
$$

$$
y(x_{\text{norm}}) = \begin{cases} 
0 & \text{if } x_{\text{norm}} < 0 \\
\frac{a}{2m}x_{\text{norm}}^2 & \text{if } 0 \leq x_{\text{norm}} < m \\
ax_{\text{norm}} + \frac{1-a}{2} & \text{if } m \leq x_{\text{norm}} < 1-m \\
1 - \frac{a}{2m}(1-x_{\text{norm}})^2 & \text{if } 1-m \leq x_{\text{norm}} < 1 \\
1 & \text{if } x_{\text{norm}} \geq 1
\end{cases}
$$


$$
d = x_{\text{hi}} - x_{\text{lo}}
$$

$$
x_{\text{norm}} = \frac{x - x_{\text{lo}}}{d}
$$

$$
a = \frac{1}{1-m}
$$

with the constraint that $m \leq \frac{d}{2}$

Bucket overflow actives when the storage of the upper layer exceeds $S_{max}$.

Overflow is defined as

$$
q_{ufof} = \Upsilon(S, S_{max}, \omega) (p - q_{sx}) 
$$

The (smooth) activation function $\Upsilon$ is a logistic sigmoid.

$$
\Upsilon(S, S_{max}, \omega) = \left[ 1 + \exp\left( \frac{S - S_{max}}{ \omega } \right) \right] ^ {-1}
$$

Where $\omega = 0.05 * S_{max}$, after [@clark2008].

## Explicit Euler

We define the column vector of states

$$
\mathbf{S}_n = \begin{bmatrix} S_1 \\ S_2 \end{bmatrix}_n^{t+1}, 
\quad 
\mathbf{S}_{n+1} = \begin{bmatrix} S_1 \\ S_2 \\ S_3 \end{bmatrix}_{n+1}^{t+1}.
$$

The explicit Euler formulation:

$$
\mathbf{S}_{t+1} = \mathbf{S}_t + F( \mathbf{S}_t ) \Delta t
$$

## Implicit Euler

$$
\mathbf{S}_{t+1} = \mathbf{S}_t + F( \mathbf{S}_{t + 1} ) \Delta t
$$

$\mathbf{S}_{t + 1}$ is unknown and present on both sides of the equation. To
find it, we formulate a system of equations. As $F$ is non-linear, this
requires iterative searching for $\mathbf{S}_{t + 1}$ using the
Newton-Raphson method, during which the following equation is solved
repeatedly: 

$$
\mathbf{J}(\mathbf{S}^{t+1}_{n})\Delta\mathbf{S}^{t+1}_n = -F(\mathbf{S}^{t+1}_{n}),
$$
 
where $\mathbf{J}$ is the two by two Jacobian

$$
\mathbf{J}(\mathbf{S}^{t+1}_n) = 
\begin{bmatrix}
\frac{\partial F_1}{\partial S_1} & \frac{\partial F_1}{\partial S_2} \\
\frac{\partial F_2}{\partial S_1} & \frac{\partial F_2}{\partial S_2}
\end{bmatrix}.
$$

Term by term, for the FUSE-070 equations:

$$
\frac{\partial F_1}{\partial S_1} = -\frac{\partial e_1}{\partial S_1} - \frac{\partial q_{12}}{\partial S_1} - \frac{\partial q_{sx}}{\partial S_1} - \frac{\partial q_{ufof}}{\partial S_1}
$$
Where:

$$
\frac{\partial e_1}{\partial S_1} = \frac{PET}{2 \phi_{tens} S_{1,max}} \left(
1 - \frac{S_1^* - 1}{ \sqrt{ (S_1^* - 1)^2 + m }}
\right)
$$

$$
\frac{\partial q_{12}}{\partial S_1} = \frac{c k_u}{S_{1,max}} \left(\frac{S_1}{S_{1,max}}\right)^{c-1}
$$

$$
\frac{\partial q_{sx}}{\partial S_1} = \frac{p b}{S_{1,max}} \left(1 - \frac{S_1}{S_{1,max}}\right)^{b-1}
$$

$\frac{\partial F_1}{\partial S_2}$ is zero as $F_1$ does not depend on $S_2$.

The next term is again the derivative of the drainage term, $\frac{\partial F_2}{\partial S_1} = \frac{\partial q_{12}}{\partial S_1}$

and finally,

$$
\frac{\partial F_2}{\partial S_2} = - \nu
$$

