# Introduction

Hydrological models remains plagued by "numerical daemons", despite clear
warnings ([@clark2009], [@kavetski2009]). Hydrologists are
generally primarily concerned with errors relating to model structure and
parameterization, rather than errors numerical aspects, even though numerical
errors may dominate. Many hydrologists have only limited familiarity with
numerical techniques and rely on ad hoc approaches when programming
hydrological models.

* Researchers often familiar with "friendly" programming langauges, not compiled

One of the promises of modular modeling frameworks (MMFs) is that they allow
for easy creation of hydrological models, varying processes or numerical
schemes: the framework supplies robust numerical schemes, error control, and
time stepping. However, these frameworks see relatively little uptake in the
hydrological research community. Instead, most conceptual model development is
programmed in "user friendly" programming languages without the use of these
frameworks. In our view, the primary issue with frameworks is that they are
limiting: an interface is provided in an interpreted language (Python, R,
Matlab) for the numerical core is often implemented in a compiled language
(Fortran, C, C++) for performance reasons. This makes combination of existing
components straightforward,

Two language problem [@bezanson2012]

